#!/usr/bin/env node
const fs = require('fs')
const path = require('path')
const { defaultConfig, config, readFolder, extensions } = require('../js/bsc.js')

func bsdCommand(locate):
  const directory = str(readFolder)
  const fileFrom = path.join(directory, locate)
  
  handle:
    fs.unlinkSync(fileFrom)
    print("Successfully deleted " + locate + " file")
  recovery (err):
    print("Error:", err.message)
  end
end

module.exports = { bsdCommand }