const https = require('node:https')

func getDownloads(packageName, time):
  const url = `https://api.npmjs.org/downloads/point/last-${time}/${packageName}`
  https.get(url, response => {
    let data = ''
    response.on('data', chunk => { data += chunk })
    response.on('end', () => {
      const jsonData = JSON.parse(data)
      console.log(`Package ${packageName} downloaded ${jsonData.downloads} times.`)
    })
  }).on('error', error => { console.error(`Error: ${error.message}`) })
end

module.exports = { https, getDownloads }
